## Numpy: Package for Multidimensional array

In [1]:
import numpy as np


In [2]:
simplelist=[6,7,9]
np.array(simplelist)

array([6, 7, 9])

In [3]:
arr=np.array([6,7,9])

In [4]:
listoflists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(listoflists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(5,65)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64])

In [7]:
np.arange(5,65,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63])

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [12]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [15]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [17]:
np.random.rand(2,4)


array([[0.64582879, 0.94131362, 0.82790077, 0.13926693],
       [0.48310823, 0.39473913, 0.93515426, 0.57618677]])

In [20]:
arr=np.random.randn(2,4)
arr

array([[-0.47318089, -1.38099315,  0.61037286,  0.09655738],
       [ 0.33671251,  0.91286493, -0.47663941, -0.19636485]])

In [21]:
np.random.randint(2,10) #10 will not be consider

5

In [22]:
np.random.randint(20,56,100)

array([28, 30, 27, 54, 50, 52, 50, 41, 22, 46, 49, 30, 22, 53, 33, 26, 23,
       36, 49, 53, 42, 26, 53, 42, 35, 26, 48, 24, 33, 22, 54, 48, 26, 32,
       36, 42, 54, 48, 40, 40, 48, 35, 53, 20, 42, 25, 20, 46, 48, 36, 29,
       39, 37, 25, 36, 46, 33, 50, 50, 29, 52, 51, 38, 38, 37, 30, 25, 34,
       24, 22, 44, 32, 36, 50, 21, 50, 23, 38, 32, 41, 48, 29, 41, 39, 28,
       31, 29, 55, 42, 53, 25, 45, 27, 55, 44, 41, 32, 52, 23, 40])

In [23]:
samplearray=np.arange(30)
samplearray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
rand_array=np.random.randint(0,100,20)
rand_array

array([93, 66, 56, 31, 84, 33, 89, 98, 18, 60, 73, 57, 39,  9,  9, 21, 56,
       75,  4, 66])

In [73]:
#samplearray.reshape(5,6)
samplearray.shape

(19,)

In [27]:
rand_array.min()

4

In [28]:
rand_array.argmin()   #index of minimum

18

In [29]:
samplearray



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [30]:
samplearray.dtype

dtype('int32')

In [31]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
a=np.random.rand(2,3)
a

array([[0.15756603, 0.20746005, 0.74984686],
       [0.36099501, 0.96529233, 0.31607906]])

In [34]:
a.T

array([[0.15756603, 0.36099501],
       [0.20746005, 0.96529233],
       [0.74984686, 0.31607906]])

In [36]:
samplearray=np.arange(10,21)
samplearray

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [37]:
samplearray[8]

18

In [38]:
samplearray[2:5]

array([12, 13, 14])

In [40]:
samplearray[1:4]=100
samplearray

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [41]:
subsetarray=samplearray[1:5]
subsetarray

array([100, 100, 100,  14])

## multidimensional array

In [42]:
import numpy as np

In [44]:
samplematrix=np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))
samplematrix

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
samplematrix[0][2]

3

In [46]:
samplematrix[2,:]

array([ 9, 10, 11, 12])

In [47]:
samplematrix[2]

array([ 9, 10, 11, 12])

### custom indexing

In [49]:
samplematrix=np.array(([30,10,1,23],[24,21,32,33],[6,76,24,7]))
samplematrix

array([[30, 10,  1, 23],
       [24, 21, 32, 33],
       [ 6, 76, 24,  7]])

In [50]:
samplematrix[:,(3,2)]  #all rows and 3,2,columns

array([[23,  1],
       [33, 32],
       [ 7, 24]])

In [51]:
samplearray=np.arange(1,20)
samplearray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [52]:
samplearray+samplearray

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [53]:
np.exp(samplearray) #exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [54]:
np.sqrt(samplearray)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [55]:
np.log(samplearray)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [56]:
np.max(samplearray)

19

In [58]:
np.argmin(samplearray)

0

In [59]:
np.square(samplearray)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)

In [60]:
np.std(samplearray)

5.477225575051661

In [61]:
np.var(samplearray)

30.0

In [62]:
np.mean(samplearray)

10.0

In [65]:
array=np.random.randn(3,4)

In [66]:
np.round(array,decimals=2)

array([[-0.89, -0.22,  1.27,  1.18],
       [-1.27, -1.01, -1.28,  1.12],
       [ 0.13, -0.64, -0.11, -0.93]])

In [68]:
sports=np.array(['golf','cricket','fbal,','cricket'])
np.unique(sports)

array(['cricket', 'fbal,', 'golf'], dtype='<U7')